import type { Metadata } from "next";
import { Poppins, Space_Grotesk } from 'next/font/google'
import "./globals.css";
import Navbar from "../app/components/common/Navbar"
// ---------- Meta -------------
export const metadata: Metadata = {
  title: "Rexify",
  description: "Generated by create next app",
};

// ---------- Fonts -------------
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})
const space  = Space_Grotesk({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${poppins.className}`}>
      <Navbar/>
      <body>{children}</body>
    </html>
  );
} 
